# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e93803675fdd11a043801fb38f53c2de994fb24ec200686fd103812d9abb7cd035b7d06fad1600ac1c6fa17fc652d3202f2806198d448b25775ec755396d8e2

test:
  secret_key_base: c0e619b16505dd3e4005fc09ce24e40f25be570e078224b9541f64e45ab33bbc0c99af0de9f3a43adb0376472acb134a055ed7cd9a19f50a66c69b360c74f89a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
